### ISSUE TITLE
scope chain code along is same content as scope lab

### ISSUE THREAD

**Issue by jonopens** [learn-co-curriculum/js-principles-scope-chain-code-along#1]
To reproduce:
1. clone down https://github.com/learn-co-students/js-principles-scope-chain-code-along-web-082817
2. clone down https://github.com/learn-co-students/js-principles-scope-lab-web-082817
3. compare tests
4. note that they are the same
5. also compare the learn.co content and note it is the same.

**Comment by DanielSeehausen** [comment]
Second this - discussed with 0828 teaching staff. Please destroy.

**Comment by drakeltheryuujin** [comment]
@DanielSeehausen destroy which one?

**Comment by drakeltheryuujin** [comment]
This is all going to get removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: 

https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
