### ISSUE TITLE
Local tests/repeat lab?

### ISSUE THREAD

**Issue by jamiegiuliano** [learn-co-curriculum/js-principles-scope-chain-code-along#10]
The local tests aren't turning green (or red) on Learn.co. Also, it looks like this lab is an almost exact copy of the Scope Lab & the answers are cloned with the Master Branch.

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
