### ISSUE TITLE
Solution branch?

### ISSUE THREAD

**Issue by KristenLeach** [learn-co-curriculum/js-principles-scope-chain-code-along#11]
Hello! This code along contains all of the same functions as the scope lab, and when you fork/clone the lesson all of the tests are already passing as instructed. I'm wondering if the solution branch is being passed as the assignment? Either way, something funny is going on with this one!

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
