### ISSUE TITLE
cant run local tests

### ISSUE THREAD

**Issue by yosayon** [learn-co-curriculum/js-principles-scope-chain-code-along#12]
unable to run local tests.

**Comment by ddhogan** [comment]
I am having the same issue: "This directory doesn't appear to have any specs in it."

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
