### ISSUE TITLE
Forking This Lab Provides The Full Solution

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/js-principles-scope-chain-code-along#13]
I'm not sure if this was intentional, given this is just a code along and not a lab, but simply forking this lab provides code that already passes the full test suite with all the solutions included.

**Comment by Perchitti** [comment]
Second this!

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
