### ISSUE TITLE
Nothing Left To Do

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/js-principles-scope-chain-code-along#14]
I'm a bit confused on this lab because the entire thing has already been coded. Is that supposed to be correct?

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.
Thanks 💙
