### ISSUE TITLE
Duplicate Lesson

### ISSUE THREAD

**Issue by AubreyNeimeier** [learn-co-curriculum/js-principles-scope-chain-code-along#15]
The code-along is nearly identical to the scoping lab. In addition, when I forked the lab, the solution was already included in its entirety. The very last test does not pass. The lab readme on learn is not updating the 'run local tests' flag no matter how many times I run it. In short, this lesson is a mess.

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
