### ISSUE TITLE
Issue with the last test.

### ISSUE THREAD

**Issue by MuhannedNoman** [learn-co-curriculum/js-principles-scope-chain-code-along#16]
When cloning this lesson the solution is already there. I deleted everything and worked on it step by step. But the last test doesn't  work no matter what I do even though the answer is correct. 
So I committed the test and my solution and moved on with my life.

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
