### ISSUE TITLE
This Lab Solved 

### ISSUE THREAD

**Issue by MERCERNYC** [learn-co-curriculum/js-principles-scope-chain-code-along#17]
Was this lab supposed to be solved when cloned? Couldn't could along because it had no errors.

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.
We'll put this recommendation in review for the next version release. My team will start batching these here: 

https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
