### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by drakeltheryuujin** [learn-co-curriculum/js-principles-scope-chain-code-along#18]
re: duplicated lesson, included solution, broken tests

Track changes have to be batched (for technical reasons) and this codealong will be removed.
This will be corrected for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

Thanks 💙

**Comment by sgharms** [comment]
Solution and tests have been fixed as of 2018-10-01
