### ISSUE TITLE
Tests won't pass

### ISSUE THREAD

**Issue by DiloromA** [learn-co-curriculum/js-principles-scope-chain-code-along#19]
No matter what you do, test won't pass. I think test is not connected to the solution.

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
