### ISSUE TITLE
Scripts not specified in package.json

### ISSUE THREAD

**Issue by marcnjaramillo** [learn-co-curriculum/js-principles-scope-chain-code-along#2]
When running `learn` encountered an error in console: `Error: no test specified` that prevented test suite from even running. The `scripts` are missing in the `package.json` file, which I had to add in from another lab.

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
