### ISSUE TITLE
solution does not pass test

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/js-principles-scope-chain-code-along#20]
Student reported today that solution does not pass tests. Should there be tests for this code-along?

**Comment by drakeltheryuujin** [comment]
Hi @d-d-d-dalia,

I'm having difficulty reproducing the issue (solution does pass), so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue I'd be happy to take a second look!

Thanks! 💙
