### ISSUE TITLE
Nearly the same as Scope Lab

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/js-principles-scope-chain-code-along#21]
Hey there, I see there was a similar issue posted in August 2018, but this is nearly the same as the Scope lab and I wouldn't label this as a code-along either.

Best.

**Comment by drakeltheryuujin** [comment]
Hi @helloamandamurphy,

We’ve built this feedback into our next major release of this section of curriculum. For technological reasons, the repo name can't easily be renamed without causing issues in Learn.  We’re targeting delivery in the first half of 2019. This will be resolved when the curriculum rewrite is released.
