### ISSUE TITLE
This code along is out of place or broken

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/js-principles-scope-chain-code-along#3]
Tests do not work. Appears to be out of place.

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
