### ISSUE TITLE
This lab is just a repeat of the previous scope lab, but it doesnt run the test.

### ISSUE THREAD

**Issue by CurlsandCode** [learn-co-curriculum/js-principles-scope-chain-code-along#4]

**Comment by joshuaneedham** [comment]
It's also preventing the competition if the entire JavaScript section due to no testing.

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
