### ISSUE TITLE
Repeat lesson

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/js-principles-scope-chain-code-along#5]
This lab appears to be a repeat of the Scope lab. Learn also won't pass any tests, but it will submit. While the repos for the Scope lab and Scope chain lab appear separately (they have different names), the substance of my Scope lab repo is automatically imported to to Scope chain lab when I open Atom. 

Here's the error message for the learn tests: 
`learn

> fsevents@1.1.2 install /Users/kmlarson/js-principles-scope-chain-code-along-v-000/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.4.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/kmlarson/.node-gyp/9.4.0/include/node/v8.h:3114:3: note: 'ForceSet' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/kmlarson/.node-gyp/9.4.0/include/node/v8config.h:321:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/kmlarson/js-principles-scope-chain-code-along-v-000/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
added 454 packages in 51.795s

> javascript-strings-lab@0.1.0 test /Users/kmlarson/js-principles-scope-chain-code-along-v-000
> echo 'Error: no test specified'

Error: no test specified
`

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
