### ISSUE TITLE
Package.json has some problems

### ISSUE THREAD

**Issue by robert-laws** [learn-co-curriculum/js-principles-scope-chain-code-along#7]
After forking this lab, I had to update the package.json file in order to get it to work properly. The repo version of package.json appeared to be missing the "scripts" field with the "postinstall" for the learn-co gem and the "test" command to start-up the browser for the tests. Also, it looked like he "learn-browser" version was wrong. It has version "^0.1.3" and I had to change it to "^0.1.13" to get the lab to work. Finally, it looks like the solution code in index.js is still part of the repo when forking it.

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
