### ISSUE TITLE
Duplicate of Scope Lab

### ISSUE THREAD

**Issue by marynavoitenko** [learn-co-curriculum/js-principles-scope-chain-code-along#8]
Hello, 
looks like Scope Chain Code Along duplicates Scope Lab:
https://learn.co/tracks/full-stack-web-development-v5/javascript/principles/scope-lab

Might be a regression issue related to V5 curriculum that happened few days ago. 

<img width="1200" alt="screen shot 2018-04-14 at 2 46 51 pm" src="https://user-images.githubusercontent.com/4255998/38771531-d25f32a2-3ff2-11e8-821d-4818521f7f14.png">
<img width="1183" alt="screen shot 2018-04-14 at 2 47 06 pm" src="https://user-images.githubusercontent.com/4255998/38771532-d26ce19a-3ff2-11e8-915a-dc63092c0fe7.png">

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
