### ISSUE TITLE
Master branch already contains passing code

### ISSUE THREAD

**Issue by thurman024** [learn-co-curriculum/js-principles-scope-chain-code-along#9]
Also, majority of the lab is a repeat of this lab from a few lessons prior -  [https://github.com/learn-co-students/js-principles-scope-lab-v-000](url)

**Comment by drakeltheryuujin** [comment]
Thanks for this feedback. Track changes have to be batched (for technical reasons) and this codealong will be removed.

We'll put this recommendation in review for the next version release. My team will start batching these here: https://github.com/learn-co-curriculum/flatiron-curriculum-online-proposals/issues/2

I'll close this one, but keep the other.

Thanks 💙
